name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: levents
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo fmt
        run: cargo fmt -- --check
      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Cargo test
        run: cargo test --all-features

  node:
    name: Node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Build
        run: pnpm build

  python:
    name: Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install package
        run: |
          pip install --upgrade pip
          pip install -e bindings/py[dev]
      - name: Lint
        run: black --check bindings/py/src bindings/py/tests
      - name: Tests
        run: pytest
        working-directory: bindings/py
